######################################################################
# Automatically generated by qmake (3.0) jeu. sept. 24 21:53:05 2015
######################################################################

TEMPLATE = app
TARGET = tp1
INCLUDEPATH += .

# Input
HEADERS += openglwindow.h SuperbPlane.cpp DirtyPlane.hpp HeightMapper.hpp HeightMapWindow.hpp
SOURCES += main.cpp openglwindow.cpp SuperbPlane.cpp DirtyPlane.cpp HeightMapper.cpp HeightMapWindow.cpp
QT += opengl
